name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "shreyasingh200297.ss@gmail.com"
          git config --global user.name "shreya20singh"

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Deploy to GitHub Pages
        run: |
          npx gh-pages -d build --branch master
